//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.dbcontext
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NekpalEntities : DbContext
    {
        public NekpalEntities()
            : base("name=NekpalEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<emloyeea> emloyeeas { get; set; }
        public virtual DbSet<login> logins { get; set; }

        public System.Data.Entity.DbSet<WebApplication3.Models.empmodel> empmodels { get; set; }

        public System.Data.Entity.DbSet<WebApplication3.Models.loginmodel> loginmodels { get; set; }
    }
}
